pipeline {
    agent any

    environment {
        PROJECT_ID = "project-43a9394e-242f-44c3-95e"
        REGION = "us-central1"
        REPO = "docker-repo"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('docker-training-main/backend') {
                    sh 'docker build -t backend:v1 .'
                }
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                docker tag backend:v1 \
                us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/backend:v1
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push \
                us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/backend:v1
                '''
            }
        }
    }
}
